### ISSUE TITLE
Peer-review Backend

### ISSUE THREAD

**Issue by xXJohamXx** [UBC-MDS/DS-Salaries#45]

**Comment by RussDim** [comment]
**Peer Review: Backend of Group 17**

Backend code included in the `app.R ` file of the group repo is very clear and well written.  Detailed comments make it easy to read and understand the underlying functionality.  

**9.** Are all the options that you can select in the widgets working correctly? Have you found some options/combinations where you got errors?

**9.1.** After reviewing carefully all options and combinations I found no mistakes.  A few minor notes are:

- You could format the data better to fix some of the year values in the plots.  For example the combination Art Type: Memorial or Monument + Neighborhood: Mount Pleasant has values in the Year Installed plot of 2009.75, 2010.00.  Because there is only one element, the plot axis is set as continuous and shows up with fractions of the year.  Same thing happens when I select the Neighborhood.  If you add something like this to your plot, it seems to fix the problem: `scale_x_continuous(breaks = seq(1950, 2020, 10))`

- One other comment: when the filters result in an empty output e.g. Memorial or Monument + Mount Pleasant and  set the sliders for the Year installed for example at 2011 and 2022 return an empty map.  Similarly when you slide the right slider down to 2009 the Everything disappears for the above combination.  This might seem like a but to the user.  It would probably be better to show empty map or show a message which saying something like: “No Art for this period with the selected criteria.”

**9.2.** Could be added reactive expressions to avoid code duplication?

The reactive elements are well structured and mutually exclusive, which makes the code very efficient already.  Each element of the app has it’s own reactive element, which works as expected.

**9.3.** Could be included dynamic UI elements or actions buttons? Or what other element - widget would you include?

The app is really well structured without being cluttered.  I like the leafletOutput for the menus which make a very efficient use of the screen.

One additional element that could add value is to have a search box for searching monuments by name. 
It could also be helpful to have the popup descriptions of each element come out when the user hovers over them instead of having to click.

These are of course, design choices, which are up to the authors and do not take away from the excellence of the backend implementation.

Overall backend is really impressive, especially considering the complicated dataset the team is using.  Great Job!
